version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  app-chat:
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
    - REDIS_URL=redis://redis:6379